apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: todo-app
  labels:
    type: vue-app
    language: js
spec:
  replicas: 3
  selector:
    matchLabels:
      type: vue-app
  template:
    metadata:
      labels:
        type: vue-app
        language: js
    spec:
      containers:
      - name: app
        image: "${IMAGE_NAME}"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    type: vue-app